name: build

on: [push]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: react-scaffolder-dependency-cache
      with:
        path: node_modules
        key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm install

  eslint:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
    - uses: actions/checkout@v2
    - name: Restore npm cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: react-scaffolder-dependency-cache-${{ hashFiles('**/package-lock.json') }}
    - name: Lint all scripts
      run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
    - uses: actions/checkout@v2
    - name: Restore npm cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: react-scaffolder-dependency-cache-${{ hashFiles('**/package-lock.json') }}
    - name: Run unit tests
      run: npm test

  test_javascript_template:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
    - uses: actions/checkout@v2
    - name: Run all checks for JavaScript template
      run: npm run test:javascript

  test_typescript_template:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
    - uses: actions/checkout@v2
    - name: Run all checks for TypeScript template
      run: npm run test:typescript
